currencies = {
    'AED': {'currency': 'UAE Dirham', 'numeric code': 784, 'minor unit': 2, 'plural name': 'UAE dirhams', 'singular name': 'UAE dirham', 'symbol': 'AED', 'narrow symbol': 'AED'},
    'AFN': {'currency': 'Afghani', 'numeric code': 971, 'minor unit': 2, 'plural name': 'Afghan afghanis', 'singular name': 'Afghan afghani', 'symbol': 'AFN', 'narrow symbol': '؋'},
    'ALL': {'currency': 'Lek', 'numeric code': 8, 'minor unit': 2, 'plural name': 'Albanian lekë', 'singular name': 'Albanian lek', 'symbol': 'ALL', 'narrow symbol': 'ALL'},
    'AMD': {'currency': 'Armenian Dram', 'numeric code': 51, 'minor unit': 2, 'plural name': 'Armenian drams', 'singular name': 'Armenian dram', 'symbol': 'AMD', 'narrow symbol': '֏'},
    'ANG': {'currency': 'Netherlands Antillean Guilder', 'numeric code': 532, 'minor unit': 2, 'plural name': 'Netherlands Antillean guilders', 'singular name': 'Netherlands Antillean guilder', 'symbol': 'ANG', 'narrow symbol': 'ANG'},
    'AOA': {'currency': 'Kwanza', 'numeric code': 973, 'minor unit': 2, 'plural name': 'Angolan kwanzas', 'singular name': 'Angolan kwanza', 'symbol': 'AOA', 'narrow symbol': 'Kz'},
    'ARS': {'currency': 'Argentine Peso', 'numeric code': 32, 'minor unit': 2, 'plural name': 'Argentine pesos', 'singular name': 'Argentine peso', 'symbol': 'ARS', 'narrow symbol': '$'},
    'AUD': {'currency': 'Australian Dollar', 'numeric code': 36, 'minor unit': 2, 'plural name': 'Australian dollars', 'singular name': 'Australian dollar', 'symbol': 'A$', 'narrow symbol': '$'},
    'AWG': {'currency': 'Aruban Florin', 'numeric code': 533, 'minor unit': 2, 'plural name': 'Aruban florin', 'singular name': 'Aruban florin', 'symbol': 'AWG', 'narrow symbol': 'G'},
    'AZN': {'currency': 'Azerbaijan Manat', 'numeric code': 944, 'minor unit': 2, 'plural name': 'Azerbaijani manats', 'singular name': 'Azerbaijani manat', 'symbol': 'AZN', 'narrow symbol': '₼'},
    'BAM': {'currency': 'Convertible Mark', 'numeric code': 977, 'minor unit': 2, 'plural name': 'Bosnia-Herzegovina convertible marks', 'singular name': 'Bosnia-Herzegovina convertible mark', 'symbol': 'BAM', 'narrow symbol': 'KM'},
    'BBD': {'currency': 'Barbados Dollar', 'numeric code': 52, 'minor unit': 2, 'plural name': 'Barbadian dollars', 'singular name': 'Barbadian dollar', 'symbol': 'BBD', 'narrow symbol': '$'},
    'BDT': {'currency': 'Taka', 'numeric code': 50, 'minor unit': 2, 'plural name': 'Bangladeshi takas', 'singular name': 'Bangladeshi taka', 'symbol': 'BDT', 'narrow symbol': '৳'},
    'BGN': {'currency': 'Bulgarian Lev', 'numeric code': 975, 'minor unit': 2, 'plural name': 'Bulgarian leva', 'singular name': 'Bulgarian lev', 'symbol': 'BGN', 'narrow symbol': 'BGN'},
    'BHD': {'currency': 'Bahraini Dinar', 'numeric code': 48, 'minor unit': 3, 'plural name': 'Bahraini dinars', 'singular name': 'Bahraini dinar', 'symbol': 'BHD', 'narrow symbol': 'BHD'},
    'BIF': {'currency': 'Burundi Franc', 'numeric code': 108, 'minor unit': 0, 'plural name': 'Burundian francs', 'singular name': 'Burundian franc', 'symbol': 'BIF', 'narrow symbol': 'BIF'},
    'BMD': {'currency': 'Bermudian Dollar', 'numeric code': 60, 'minor unit': 2, 'plural name': 'Bermudan dollars', 'singular name': 'Bermudan dollar', 'symbol': 'BMD', 'narrow symbol': '$'},
    'BND': {'currency': 'Brunei Dollar', 'numeric code': 96, 'minor unit': 2, 'plural name': 'Brunei dollars', 'singular name': 'Brunei dollar', 'symbol': 'BND', 'narrow symbol': '$'},
    'BOB': {'currency': 'Boliviano', 'numeric code': 68, 'minor unit': 2, 'plural name': 'Bolivian bolivianos', 'singular name': 'Bolivian boliviano', 'symbol': 'BOB', 'narrow symbol': 'Bs'},
    'BOV': {'currency': 'Mvdol', 'numeric code': 984, 'minor unit': 2, 'plural name': 'Bolivian mvdols', 'singular name': 'Bolivian mvdol', 'symbol': 'BOV', 'narrow symbol': 'BOV'},
    'BRL': {'currency': 'Brazilian Real', 'numeric code': 986, 'minor unit': 2, 'plural name': 'Brazilian reals', 'singular name': 'Brazilian real', 'symbol': 'R$', 'narrow symbol': 'R$'},
    'BSD': {'currency': 'Bahamian Dollar', 'numeric code': 44, 'minor unit': 2, 'plural name': 'Bahamian dollars', 'singular name': 'Bahamian dollar', 'symbol': 'BSD', 'narrow symbol': '$'},
    'BTN': {'currency': 'Ngultrum', 'numeric code': 64, 'minor unit': 2, 'plural name': 'Bhutanese ngultrums', 'singular name': 'Bhutanese ngultrum', 'symbol': 'BTN', 'narrow symbol': 'BTN'},
    'BWP': {'currency': 'Pula', 'numeric code': 72, 'minor unit': 2, 'plural name': 'Botswanan pulas', 'singular name': 'Botswanan pula', 'symbol': 'BWP', 'narrow symbol': 'P'},
    'BYN': {'currency': 'Belarusian Ruble', 'numeric code': 933, 'minor unit': 2, 'plural name': 'Belarusian rubles', 'singular name': 'Belarusian ruble', 'symbol': 'BYN', 'narrow symbol': 'р.'},
    'BZD': {'currency': 'Belize Dollar', 'numeric code': 84, 'minor unit': 2, 'plural name': 'Belize dollars', 'singular name': 'Belize dollar', 'symbol': 'BZD', 'narrow symbol': '$'},
    'CAD': {'currency': 'Canadian Dollar', 'numeric code': 124, 'minor unit': 2, 'plural name': 'Canadian dollars', 'singular name': 'Canadian dollar', 'symbol': 'CA$', 'narrow symbol': '$'},
    'CDF': {'currency': 'Congolese Franc', 'numeric code': 976, 'minor unit': 2, 'plural name': 'Congolese francs', 'singular name': 'Congolese franc', 'symbol': 'CDF', 'narrow symbol': 'CDF'},
    'CHE': {'currency': 'WIR Euro', 'numeric code': 947, 'minor unit': 2, 'plural name': 'WIR euros', 'singular name': 'WIR euro', 'symbol': 'CHE', 'narrow symbol': 'CHE'},
    'CHF': {'currency': 'Swiss Franc', 'numeric code': 756, 'minor unit': 2, 'plural name': 'Swiss francs', 'singular name': 'Swiss franc', 'symbol': 'CHF', 'narrow symbol': 'CHF'},
    'CHW': {'currency': 'WIR Franc', 'numeric code': 948, 'minor unit': 2, 'plural name': 'WIR francs', 'singular name': 'WIR franc', 'symbol': 'CHW', 'narrow symbol': 'CHW'},
    'CLF': {'currency': 'Unidad de Fomento', 'numeric code': 990, 'minor unit': 4, 'plural name': 'Chilean units of account (UF)', 'singular name': 'Chilean unit of account (UF)', 'symbol': 'CLF', 'narrow symbol': 'CLF'},
    'CLP': {'currency': 'Chilean Peso', 'numeric code': 152, 'minor unit': 0, 'plural name': 'Chilean pesos', 'singular name': 'Chilean peso', 'symbol': 'CLP', 'narrow symbol': '$'},
    'CNY': {'currency': 'Yuan Renminbi', 'numeric code': 156, 'minor unit': 2, 'plural name': 'Chinese yuan', 'singular name': 'Chinese yuan', 'symbol': 'CN¥', 'narrow symbol': '¥'},
    'COP': {'currency': 'Colombian Peso', 'numeric code': 170, 'minor unit': 2, 'plural name': 'Colombian pesos', 'singular name': 'Colombian peso', 'symbol': 'COP', 'narrow symbol': '$'},
    'COU': {'currency': 'Unidad de Valor Real', 'numeric code': 970, 'minor unit': 2, 'plural name': 'Colombian real value units', 'singular name': 'Colombian real value unit', 'symbol': 'COU', 'narrow symbol': 'COU'},
    'CRC': {'currency': 'Costa Rican Colon', 'numeric code': 188, 'minor unit': 2, 'plural name': 'Costa Rican colóns', 'singular name': 'Costa Rican colón', 'symbol': 'CRC', 'narrow symbol': '₡'},
    'CUC': {'currency': 'Peso Convertible', 'numeric code': 931, 'minor unit': 2, 'plural name': 'Cuban convertible pesos', 'singular name': 'Cuban convertible peso', 'symbol': 'CUC', 'narrow symbol': '$'},
    'CUP': {'currency': 'Cuban Peso', 'numeric code': 192, 'minor unit': 2, 'plural name': 'Cuban pesos', 'singular name': 'Cuban peso', 'symbol': 'CUP', 'narrow symbol': '$'},
    'CVE': {'currency': 'Cabo Verde Escudo', 'numeric code': 132, 'minor unit': 2, 'plural name': 'Cape Verdean escudos', 'singular name': 'Cape Verdean escudo', 'symbol': 'CVE', 'narrow symbol': 'CVE'},
    'CZK': {'currency': 'Czech Koruna', 'numeric code': 203, 'minor unit': 2, 'plural name': 'Czech korunas', 'singular name': 'Czech koruna', 'symbol': 'CZK', 'narrow symbol': 'Kč'},
    'DJF': {'currency': 'Djibouti Franc', 'numeric code': 262, 'minor unit': 0, 'plural name': 'Djiboutian francs', 'singular name': 'Djiboutian franc', 'symbol': 'DJF', 'narrow symbol': 'DJF'},
    'DKK': {'currency': 'Danish Krone', 'numeric code': 208, 'minor unit': 2, 'plural name': 'Danish kroner', 'singular name': 'Danish krone', 'symbol': 'DKK', 'narrow symbol': 'kr'},
    'DOP': {'currency': 'Dominican Peso', 'numeric code': 214, 'minor unit': 2, 'plural name': 'Dominican pesos', 'singular name': 'Dominican peso', 'symbol': 'DOP', 'narrow symbol': '$'},
    'DZD': {'currency': 'Algerian Dinar', 'numeric code': 12, 'minor unit': 2, 'plural name': 'Algerian dinars', 'singular name': 'Algerian dinar', 'symbol': 'DZD', 'narrow symbol': 'DZD'},
    'EGP': {'currency': 'Egyptian Pound', 'numeric code': 818, 'minor unit': 2, 'plural name': 'Egyptian pounds', 'singular name': 'Egyptian pound', 'symbol': 'EGP', 'narrow symbol': 'E£'},
    'ERN': {'currency': 'Nakfa', 'numeric code': 232, 'minor unit': 2, 'plural name': 'Eritrean nakfas', 'singular name': 'Eritrean nakfa', 'symbol': 'ERN', 'narrow symbol': 'ERN'},
    'ETB': {'currency': 'Ethiopian Birr', 'numeric code': 230, 'minor unit': 2, 'plural name': 'Ethiopian birrs', 'singular name': 'Ethiopian birr', 'symbol': 'ETB', 'narrow symbol': 'ETB'},
    'EUR': {'currency': 'Euro', 'numeric code': 978, 'minor unit': 2, 'plural name': 'Euros', 'singular name': 'Euro', 'symbol': '€', 'narrow symbol': '€'},
    'FJD': {'currency': 'Fiji Dollar', 'numeric code': 242, 'minor unit': 2, 'plural name': 'Fijian dollars', 'singular name': 'Fijian dollar', 'symbol': 'FJD', 'narrow symbol': '$'},
    'FKP': {'currency': 'Falkland Islands Pound', 'numeric code': 238, 'minor unit': 2, 'plural name': 'Falkland Islands pounds', 'singular name': 'Falkland Islands pound', 'symbol': 'FKP', 'narrow symbol': '£'},
    'GBP': {'currency': 'Pound Sterling', 'numeric code': 826, 'minor unit': 2, 'plural name': 'British pounds', 'singular name': 'British pound', 'symbol': '£', 'narrow symbol': '£'},
    'GEL': {'currency': 'Lari', 'numeric code': 981, 'minor unit': 2, 'plural name': 'Georgian laris', 'singular name': 'Georgian lari', 'symbol': 'GEL', 'narrow symbol': '₾'},
    'GHS': {'currency': 'Ghana Cedi', 'numeric code': 936, 'minor unit': 2, 'plural name': 'Ghanaian cedis', 'singular name': 'Ghanaian cedi', 'symbol': 'GHS', 'narrow symbol': 'GH₵'},
    'GIP': {'currency': 'Gibraltar Pound', 'numeric code': 292, 'minor unit': 2, 'plural name': 'Gibraltar pounds', 'singular name': 'Gibraltar pound', 'symbol': 'GIP', 'narrow symbol': '£'},
    'GMD': {'currency': 'Dalasi', 'numeric code': 270, 'minor unit': 2, 'plural name': 'Gambian dalasis', 'singular name': 'Gambian dalasi', 'symbol': 'GMD', 'narrow symbol': 'GMD'},
    'GNF': {'currency': 'Guinean Franc', 'numeric code': 324, 'minor unit': 0, 'plural name': 'Guinean francs', 'singular name': 'Guinean franc', 'symbol': 'GNF', 'narrow symbol': 'FG'},
    'GTQ': {'currency': 'Quetzal', 'numeric code': 320, 'minor unit': 2, 'plural name': 'Guatemalan quetzals', 'singular name': 'Guatemalan quetzal', 'symbol': 'GTQ', 'narrow symbol': 'Q'},
    'GYD': {'currency': 'Guyana Dollar', 'numeric code': 328, 'minor unit': 2, 'plural name': 'Guyanaese dollars', 'singular name': 'Guyanaese dollar', 'symbol': 'GYD', 'narrow symbol': '$'},
    'HKD': {'currency': 'Hong Kong Dollar', 'numeric code': 344, 'minor unit': 2, 'plural name': 'Hong Kong dollars', 'singular name': 'Hong Kong dollar', 'symbol': 'HK$', 'narrow symbol': '$'},
    'HNL': {'currency': 'Lempira', 'numeric code': 340, 'minor unit': 2, 'plural name': 'Honduran lempiras', 'singular name': 'Honduran lempira', 'symbol': 'HNL', 'narrow symbol': 'L'},
    'HRK': {'currency': 'Kuna', 'numeric code': 191, 'minor unit': 2, 'plural name': 'Croatian kunas', 'singular name': 'Croatian kuna', 'symbol': 'HRK', 'narrow symbol': 'kn'},
    'HTG': {'currency': 'Gourde', 'numeric code': 332, 'minor unit': 2, 'plural name': 'Haitian gourdes', 'singular name': 'Haitian gourde', 'symbol': 'HTG', 'narrow symbol': 'HTG'},
    'HUF': {'currency': 'Forint', 'numeric code': 348, 'minor unit': 2, 'plural name': 'Hungarian forints', 'singular name': 'Hungarian forint', 'symbol': 'HUF', 'narrow symbol': 'Ft'},
    'IDR': {'currency': 'Rupiah', 'numeric code': 360, 'minor unit': 2, 'plural name': 'Indonesian rupiahs', 'singular name': 'Indonesian rupiah', 'symbol': 'IDR', 'narrow symbol': 'Rp'},
    'ILS': {'currency': 'New Israeli Sheqel', 'numeric code': 376, 'minor unit': 2, 'plural name': 'Israeli new shekels', 'singular name': 'Israeli new shekel', 'symbol': '₪', 'narrow symbol': '₪'},
    'INR': {'currency': 'Indian Rupee', 'numeric code': 356, 'minor unit': 2, 'plural name': 'Indian rupees', 'singular name': 'Indian rupee', 'symbol': '₹', 'narrow symbol': '₹'},
    'IQD': {'currency': 'Iraqi Dinar', 'numeric code': 368, 'minor unit': 3, 'plural name': 'Iraqi dinars', 'singular name': 'Iraqi dinar', 'symbol': 'IQD', 'narrow symbol': 'IQD'},
    'IRR': {'currency': 'Iranian Rial', 'numeric code': 364, 'minor unit': 2, 'plural name': 'Iranian rials', 'singular name': 'Iranian rial', 'symbol': 'IRR', 'narrow symbol': 'IRR'},
    'ISK': {'currency': 'Iceland Krona', 'numeric code': 352, 'minor unit': 0, 'plural name': 'Icelandic krónur', 'singular name': 'Icelandic króna', 'symbol': 'ISK', 'narrow symbol': 'kr'},
    'JMD': {'currency': 'Jamaican Dollar', 'numeric code': 388, 'minor unit': 2, 'plural name': 'Jamaican dollars', 'singular name': 'Jamaican dollar', 'symbol': 'JMD', 'narrow symbol': '$'},
    'JOD': {'currency': 'Jordanian Dinar', 'numeric code': 400, 'minor unit': 3, 'plural name': 'Jordanian dinars', 'singular name': 'Jordanian dinar', 'symbol': 'JOD', 'narrow symbol': 'JOD'},
    'JPY': {'currency': 'Yen', 'numeric code': 392, 'minor unit': 0, 'plural name': 'Japanese yen', 'singular name': 'Japanese yen', 'symbol': '¥', 'narrow symbol': '¥'},
    'KES': {'currency': 'Kenyan Shilling', 'numeric code': 404, 'minor unit': 2, 'plural name': 'Kenyan shillings', 'singular name': 'Kenyan shilling', 'symbol': 'KES', 'narrow symbol': 'KES'},
    'KGS': {'currency': 'Som', 'numeric code': 417, 'minor unit': 2, 'plural name': 'Kyrgystani soms', 'singular name': 'Kyrgystani som', 'symbol': 'KGS', 'narrow symbol': 'KGS'},
    'KHR': {'currency': 'Riel', 'numeric code': 116, 'minor unit': 2, 'plural name': 'Cambodian riels', 'singular name': 'Cambodian riel', 'symbol': 'KHR', 'narrow symbol': '៛'},
    'KMF': {'currency': 'Comorian Franc ', 'numeric code': 174, 'minor unit': 0, 'plural name': 'Comorian francs', 'singular name': 'Comorian franc', 'symbol': 'KMF', 'narrow symbol': 'CF'},
    'KPW': {'currency': 'North Korean Won', 'numeric code': 408, 'minor unit': 2, 'plural name': 'North Korean won', 'singular name': 'North Korean won', 'symbol': 'KPW', 'narrow symbol': '₩'},
    'KRW': {'currency': 'Won', 'numeric code': 410, 'minor unit': 0, 'plural name': 'South Korean won', 'singular name': 'South Korean won', 'symbol': '₩', 'narrow symbol': '₩'},
    'KWD': {'currency': 'Kuwaiti Dinar', 'numeric code': 414, 'minor unit': 3, 'plural name': 'Kuwaiti dinars', 'singular name': 'Kuwaiti dinar', 'symbol': 'KWD', 'narrow symbol': 'KWD'},
    'KYD': {'currency': 'Cayman Islands Dollar', 'numeric code': 136, 'minor unit': 2, 'plural name': 'Cayman Islands dollars', 'singular name': 'Cayman Islands dollar', 'symbol': 'KYD', 'narrow symbol': '$'},
    'KZT': {'currency': 'Tenge', 'numeric code': 398, 'minor unit': 2, 'plural name': 'Kazakhstani tenges', 'singular name': 'Kazakhstani tenge', 'symbol': 'KZT', 'narrow symbol': '₸'},
    'LAK': {'currency': 'Lao Kip', 'numeric code': 418, 'minor unit': 2, 'plural name': 'Laotian kips', 'singular name': 'Laotian kip', 'symbol': 'LAK', 'narrow symbol': '₭'},
    'LBP': {'currency': 'Lebanese Pound', 'numeric code': 422, 'minor unit': 2, 'plural name': 'Lebanese pounds', 'singular name': 'Lebanese pound', 'symbol': 'LBP', 'narrow symbol': 'L£'},
    'LKR': {'currency': 'Sri Lanka Rupee', 'numeric code': 144, 'minor unit': 2, 'plural name': 'Sri Lankan rupees', 'singular name': 'Sri Lankan rupee', 'symbol': 'LKR', 'narrow symbol': 'Rs'},
    'LRD': {'currency': 'Liberian Dollar', 'numeric code': 430, 'minor unit': 2, 'plural name': 'Liberian dollars', 'singular name': 'Liberian dollar', 'symbol': 'LRD', 'narrow symbol': '$'},
    'LSL': {'currency': 'Loti', 'numeric code': 426, 'minor unit': 2, 'plural name': 'Lesotho lotis', 'singular name': 'Lesotho loti', 'symbol': 'LSL', 'narrow symbol': 'LSL'},
    'LYD': {'currency': 'Libyan Dinar', 'numeric code': 434, 'minor unit': 3, 'plural name': 'Libyan dinars', 'singular name': 'Libyan dinar', 'symbol': 'LYD', 'narrow symbol': 'LYD'},
    'MAD': {'currency': 'Moroccan Dirham', 'numeric code': 504, 'minor unit': 2, 'plural name': 'Moroccan dirhams', 'singular name': 'Moroccan dirham', 'symbol': 'MAD', 'narrow symbol': 'MAD'},
    'MDL': {'currency': 'Moldovan Leu', 'numeric code': 498, 'minor unit': 2, 'plural name': 'Moldovan lei', 'singular name': 'Moldovan leu', 'symbol': 'MDL', 'narrow symbol': 'MDL'},
    'MGA': {'currency': 'Malagasy Ariary', 'numeric code': 969, 'minor unit': 2, 'plural name': 'Malagasy ariaries', 'singular name': 'Malagasy ariary', 'symbol': 'MGA', 'narrow symbol': 'Ar'},
    'MKD': {'currency': 'Denar', 'numeric code': 807, 'minor unit': 2, 'plural name': 'Macedonian denari', 'singular name': 'Macedonian denar', 'symbol': 'MKD', 'narrow symbol': 'MKD'},
    'MMK': {'currency': 'Kyat', 'numeric code': 104, 'minor unit': 2, 'plural name': 'Myanmar kyats', 'singular name': 'Myanmar kyat', 'symbol': 'MMK', 'narrow symbol': 'K'},
    'MNT': {'currency': 'Tugrik', 'numeric code': 496, 'minor unit': 2, 'plural name': 'Mongolian tugriks', 'singular name': 'Mongolian tugrik', 'symbol': 'MNT', 'narrow symbol': '₮'},
    'MOP': {'currency': 'Pataca', 'numeric code': 446, 'minor unit': 2, 'plural name': 'Macanese patacas', 'singular name': 'Macanese pataca', 'symbol': 'MOP', 'narrow symbol': 'MOP'},
    'MRU': {'currency': 'Ouguiya', 'numeric code': 929, 'minor unit': 2, 'plural name': 'Mauritanian ouguiyas', 'singular name': 'Mauritanian ouguiya', 'symbol': 'MRU', 'narrow symbol': 'MRU'},
    'MUR': {'currency': 'Mauritius Rupee', 'numeric code': 480, 'minor unit': 2, 'plural name': 'Mauritian rupees', 'singular name': 'Mauritian rupee', 'symbol': 'MUR', 'narrow symbol': 'Rs'},
    'MVR': {'currency': 'Rufiyaa', 'numeric code': 462, 'minor unit': 2, 'plural name': 'Maldivian rufiyaas', 'singular name': 'Maldivian rufiyaa', 'symbol': 'MVR', 'narrow symbol': 'MVR'},
    'MWK': {'currency': 'Malawi Kwacha', 'numeric code': 454, 'minor unit': 2, 'plural name': 'Malawian kwachas', 'singular name': 'Malawian kwacha', 'symbol': 'MWK', 'narrow symbol': 'MWK'},
    'MXN': {'currency': 'Mexican Peso', 'numeric code': 484, 'minor unit': 2, 'plural name': 'Mexican pesos', 'singular name': 'Mexican peso', 'symbol': 'MX$', 'narrow symbol': '$'},
    'MXV': {'currency': 'Mexican Unidad de Inversion (UDI)', 'numeric code': 979, 'minor unit': 2, 'plural name': 'Mexican investment units', 'singular name': 'Mexican investment unit', 'symbol': 'MXV', 'narrow symbol': 'MXV'},
    'MYR': {'currency': 'Malaysian Ringgit', 'numeric code': 458, 'minor unit': 2, 'plural name': 'Malaysian ringgits', 'singular name': 'Malaysian ringgit', 'symbol': 'MYR', 'narrow symbol': 'RM'},
    'MZN': {'currency': 'Mozambique Metical', 'numeric code': 943, 'minor unit': 2, 'plural name': 'Mozambican meticals', 'singular name': 'Mozambican metical', 'symbol': 'MZN', 'narrow symbol': 'MZN'},
    'NAD': {'currency': 'Namibia Dollar', 'numeric code': 516, 'minor unit': 2, 'plural name': 'Namibian dollars', 'singular name': 'Namibian dollar', 'symbol': 'NAD', 'narrow symbol': '$'},
    'NGN': {'currency': 'Naira', 'numeric code': 566, 'minor unit': 2, 'plural name': 'Nigerian nairas', 'singular name': 'Nigerian naira', 'symbol': 'NGN', 'narrow symbol': '₦'},
    'NIO': {'currency': 'Cordoba Oro', 'numeric code': 558, 'minor unit': 2, 'plural name': 'Nicaraguan córdobas', 'singular name': 'Nicaraguan córdoba', 'symbol': 'NIO', 'narrow symbol': 'C$'},
    'NOK': {'currency': 'Norwegian Krone', 'numeric code': 578, 'minor unit': 2, 'plural name': 'Norwegian kroner', 'singular name': 'Norwegian krone', 'symbol': 'NOK', 'narrow symbol': 'kr'},
    'NPR': {'currency': 'Nepalese Rupee', 'numeric code': 524, 'minor unit': 2, 'plural name': 'Nepalese rupees', 'singular name': 'Nepalese rupee', 'symbol': 'NPR', 'narrow symbol': 'Rs'},
    'NZD': {'currency': 'New Zealand Dollar', 'numeric code': 554, 'minor unit': 2, 'plural name': 'New Zealand dollars', 'singular name': 'New Zealand dollar', 'symbol': 'NZ$', 'narrow symbol': '$'},
    'OMR': {'currency': 'Rial Omani', 'numeric code': 512, 'minor unit': 3, 'plural name': 'Omani rials', 'singular name': 'Omani rial', 'symbol': 'OMR', 'narrow symbol': 'OMR'},
    'PAB': {'currency': 'Balboa', 'numeric code': 590, 'minor unit': 2, 'plural name': 'Panamanian balboas', 'singular name': 'Panamanian balboa', 'symbol': 'PAB', 'narrow symbol': 'PAB'},
    'PEN': {'currency': 'Sol', 'numeric code': 604, 'minor unit': 2, 'plural name': 'Peruvian soles', 'singular name': 'Peruvian sol', 'symbol': 'PEN', 'narrow symbol': 'PEN'},
    'PGK': {'currency': 'Kina', 'numeric code': 598, 'minor unit': 2, 'plural name': 'Papua New Guinean kina', 'singular name': 'Papua New Guinean kina', 'symbol': 'PGK', 'narrow symbol': 'K'},
    'PHP': {'currency': 'Philippine Peso', 'numeric code': 608, 'minor unit': 2, 'plural name': 'Philippine pisos', 'singular name': 'Philippine piso', 'symbol': 'PHP', 'narrow symbol': '₱'},
    'PKR': {'currency': 'Pakistan Rupee', 'numeric code': 586, 'minor unit': 2, 'plural name': 'Pakistani rupees', 'singular name': 'Pakistani rupee', 'symbol': 'PKR', 'narrow symbol': 'Rs'},
    'PLN': {'currency': 'Zloty', 'numeric code': 985, 'minor unit': 2, 'plural name': 'Polish zlotys', 'singular name': 'Polish zloty', 'symbol': 'PLN', 'narrow symbol': 'zł'},
    'PYG': {'currency': 'Guarani', 'numeric code': 600, 'minor unit': 0, 'plural name': 'Paraguayan guaranis', 'singular name': 'Paraguayan guarani', 'symbol': 'PYG', 'narrow symbol': '₲'},
    'QAR': {'currency': 'Qatari Rial', 'numeric code': 634, 'minor unit': 2, 'plural name': 'Qatari rials', 'singular name': 'Qatari rial', 'symbol': 'QAR', 'narrow symbol': 'QAR'},
    'RON': {'currency': 'Romanian Leu', 'numeric code': 946, 'minor unit': 2, 'plural name': 'Romanian lei', 'singular name': 'Romanian leu', 'symbol': 'RON', 'narrow symbol': 'lei'},
    'RSD': {'currency': 'Serbian Dinar', 'numeric code': 941, 'minor unit': 2, 'plural name': 'Serbian dinars', 'singular name': 'Serbian dinar', 'symbol': 'RSD', 'narrow symbol': 'RSD'},
    'RUB': {'currency': 'Russian Ruble', 'numeric code': 643, 'minor unit': 2, 'plural name': 'Russian rubles', 'singular name': 'Russian ruble', 'symbol': 'RUB', 'narrow symbol': '₽'},
    'RWF': {'currency': 'Rwanda Franc', 'numeric code': 646, 'minor unit': 0, 'plural name': 'Rwandan francs', 'singular name': 'Rwandan franc', 'symbol': 'RWF', 'narrow symbol': 'RF'},
    'SAR': {'currency': 'Saudi Riyal', 'numeric code': 682, 'minor unit': 2, 'plural name': 'Saudi riyals', 'singular name': 'Saudi riyal', 'symbol': 'SAR', 'narrow symbol': 'SAR'},
    'SBD': {'currency': 'Solomon Islands Dollar', 'numeric code': 90, 'minor unit': 2, 'plural name': 'Solomon Islands dollars', 'singular name': 'Solomon Islands dollar', 'symbol': 'SBD', 'narrow symbol': '$'},
    'SCR': {'currency': 'Seychelles Rupee', 'numeric code': 690, 'minor unit': 2, 'plural name': 'Seychellois rupees', 'singular name': 'Seychellois rupee', 'symbol': 'SCR', 'narrow symbol': 'SCR'},
    'SDG': {'currency': 'Sudanese Pound', 'numeric code': 938, 'minor unit': 2, 'plural name': 'Sudanese pounds', 'singular name': 'Sudanese pound', 'symbol': 'SDG', 'narrow symbol': 'SDG'},
    'SEK': {'currency': 'Swedish Krona', 'numeric code': 752, 'minor unit': 2, 'plural name': 'Swedish kronor', 'singular name': 'Swedish krona', 'symbol': 'SEK', 'narrow symbol': 'kr'},
    'SGD': {'currency': 'Singapore Dollar', 'numeric code': 702, 'minor unit': 2, 'plural name': 'Singapore dollars', 'singular name': 'Singapore dollar', 'symbol': 'SGD', 'narrow symbol': '$'},
    'SHP': {'currency': 'Saint Helena Pound', 'numeric code': 654, 'minor unit': 2, 'plural name': 'St. Helena pounds', 'singular name': 'St. Helena pound', 'symbol': 'SHP', 'narrow symbol': '£'},
    'SLL': {'currency': 'Leone', 'numeric code': 694, 'minor unit': 2, 'plural name': 'Sierra Leonean leones', 'singular name': 'Sierra Leonean leone', 'symbol': 'SLL', 'narrow symbol': 'SLL'},
    'SOS': {'currency': 'Somali Shilling', 'numeric code': 706, 'minor unit': 2, 'plural name': 'Somali shillings', 'singular name': 'Somali shilling', 'symbol': 'SOS', 'narrow symbol': 'SOS'},
    'SRD': {'currency': 'Surinam Dollar', 'numeric code': 968, 'minor unit': 2, 'plural name': 'Surinamese dollars', 'singular name': 'Surinamese dollar', 'symbol': 'SRD', 'narrow symbol': '$'},
    'SSP': {'currency': 'South Sudanese Pound', 'numeric code': 728, 'minor unit': 2, 'plural name': 'South Sudanese pounds', 'singular name': 'South Sudanese pound', 'symbol': 'SSP', 'narrow symbol': '£'},
    'STN': {'currency': 'Dobra', 'numeric code': 930, 'minor unit': 2, 'plural name': 'São Tomé & Príncipe dobras', 'singular name': 'São Tomé & Príncipe dobra', 'symbol': 'STN', 'narrow symbol': 'Db'},
    'SVC': {'currency': 'El Salvador Colon', 'numeric code': 222, 'minor unit': 2, 'plural name': 'Salvadoran colones', 'singular name': 'Salvadoran colón', 'symbol': 'SVC', 'narrow symbol': 'SVC'},
    'SYP': {'currency': 'Syrian Pound', 'numeric code': 760, 'minor unit': 2, 'plural name': 'Syrian pounds', 'singular name': 'Syrian pound', 'symbol': 'SYP', 'narrow symbol': '£'},
    'SZL': {'currency': 'Lilangeni', 'numeric code': 748, 'minor unit': 2, 'plural name': 'Swazi emalangeni', 'singular name': 'Swazi lilangeni', 'symbol': 'SZL', 'narrow symbol': 'SZL'},
    'THB': {'currency': 'Baht', 'numeric code': 764, 'minor unit': 2, 'plural name': 'Thai baht', 'singular name': 'Thai baht', 'symbol': 'THB', 'narrow symbol': '฿'},
    'TJS': {'currency': 'Somoni', 'numeric code': 972, 'minor unit': 2, 'plural name': 'Tajikistani somonis', 'singular name': 'Tajikistani somoni', 'symbol': 'TJS', 'narrow symbol': 'TJS'},
    'TMT': {'currency': 'Turkmenistan New Manat', 'numeric code': 934, 'minor unit': 2, 'plural name': 'Turkmenistani manat', 'singular name': 'Turkmenistani manat', 'symbol': 'TMT', 'narrow symbol': 'TMT'},
    'TND': {'currency': 'Tunisian Dinar', 'numeric code': 788, 'minor unit': 3, 'plural name': 'Tunisian dinars', 'singular name': 'Tunisian dinar', 'symbol': 'TND', 'narrow symbol': 'TND'},
    'TOP': {'currency': 'Pa’anga', 'numeric code': 776, 'minor unit': 2, 'plural name': 'Tongan paʻanga', 'singular name': 'Tongan paʻanga', 'symbol': 'TOP', 'narrow symbol': '$'},
    'TRY': {'currency': 'Turkish Lira', 'numeric code': 949, 'minor unit': 2, 'plural name': 'Turkish Lira', 'singular name': 'Turkish lira', 'symbol': 'TRY', 'narrow symbol': '₺'},
    'TTD': {'currency': 'Trinidad and Tobago Dollar', 'numeric code': 780, 'minor unit': 2, 'plural name': 'Trinidad & Tobago dollars', 'singular name': 'Trinidad & Tobago dollar', 'symbol': 'TTD', 'narrow symbol': '$'},
    'TWD': {'currency': 'New Taiwan Dollar', 'numeric code': 901, 'minor unit': 2, 'plural name': 'New Taiwan dollars', 'singular name': 'New Taiwan dollar', 'symbol': 'NT$', 'narrow symbol': '$'},
    'TZS': {'currency': 'Tanzanian Shilling', 'numeric code': 834, 'minor unit': 2, 'plural name': 'Tanzanian shillings', 'singular name': 'Tanzanian shilling', 'symbol': 'TZS', 'narrow symbol': 'TZS'},
    'UAH': {'currency': 'Hryvnia', 'numeric code': 980, 'minor unit': 2, 'plural name': 'Ukrainian hryvnias', 'singular name': 'Ukrainian hryvnia', 'symbol': 'UAH', 'narrow symbol': '₴'},
    'UGX': {'currency': 'Uganda Shilling', 'numeric code': 800, 'minor unit': 0, 'plural name': 'Ugandan shillings', 'singular name': 'Ugandan shilling', 'symbol': 'UGX', 'narrow symbol': 'UGX'},
    'USD': {'currency': 'US Dollar', 'numeric code': 840, 'minor unit': 2, 'plural name': 'US dollars', 'singular name': 'US dollar', 'symbol': '$', 'narrow symbol': '$'},
    'USN': {'currency': 'US Dollar (Next day)', 'numeric code': 997, 'minor unit': 2, 'plural name': 'US dollars (next day)', 'singular name': 'US dollar (next day)', 'symbol': 'USN', 'narrow symbol': 'USN'},
    'UYI': {'currency': 'Uruguay Peso en Unidades Indexadas (UI)', 'numeric code': 940, 'minor unit': 0, 'plural name': 'Uruguayan pesos (indexed units)', 'singular name': 'Uruguayan peso (indexed units)', 'symbol': 'UYI', 'narrow symbol': 'UYI'},
    'UYU': {'currency': 'Peso Uruguayo', 'numeric code': 858, 'minor unit': 2, 'plural name': 'Uruguayan pesos', 'singular name': 'Uruguayan peso', 'symbol': 'UYU', 'narrow symbol': '$'},
    'UYW': {'currency': 'Unidad Previsional', 'numeric code': 927, 'minor unit': 4, 'plural name': 'Uruguayan nominal wage index units', 'singular name': 'Uruguayan nominal wage index unit', 'symbol': 'UYW', 'narrow symbol': 'UYW'},
    'UZS': {'currency': 'Uzbekistan Sum', 'numeric code': 860, 'minor unit': 2, 'plural name': 'Uzbekistani som', 'singular name': 'Uzbekistani som', 'symbol': 'UZS', 'narrow symbol': 'S'},
    'VES': {'currency': 'Bolívar Soberano', 'numeric code': 928, 'minor unit': 2, 'plural name': 'Venezuelan bolívars', 'singular name': 'Venezuelan bolívar', 'symbol': 'VES', 'narrow symbol': 'VES'},
    'VND': {'currency': 'Dong', 'numeric code': 704, 'minor unit': 0, 'plural name': 'Vietnamese dong', 'singular name': 'Vietnamese dong', 'symbol': '₫', 'narrow symbol': '₫'},
    'VUV': {'currency': 'Vatu', 'numeric code': 548, 'minor unit': 0, 'plural name': 'Vanuatu vatus', 'singular name': 'Vanuatu vatu', 'symbol': 'VUV', 'narrow symbol': 'VUV'},
    'WST': {'currency': 'Tala', 'numeric code': 882, 'minor unit': 2, 'plural name': 'Samoan tala', 'singular name': 'Samoan tala', 'symbol': 'WST', 'narrow symbol': 'T'},
    'XAF': {'currency': 'CFA Franc BEAC', 'numeric code': 950, 'minor unit': 0, 'plural name': 'Central African CFA francs', 'singular name': 'Central African CFA franc', 'symbol': 'FCFA', 'narrow symbol': 'FCFA'},
    'XCD': {'currency': 'East Caribbean Dollar', 'numeric code': 951, 'minor unit': 2, 'plural name': 'East Caribbean dollars', 'singular name': 'East Caribbean dollar', 'symbol': 'EC$', 'narrow symbol': '$'},
    'XOF': {'currency': 'CFA Franc BCEAO', 'numeric code': 952, 'minor unit': 0, 'plural name': 'West African CFA francs', 'singular name': 'West African CFA franc', 'symbol': 'CFA', 'narrow symbol': 'CFA'},
    'XPF': {'currency': 'CFP Franc', 'numeric code': 953, 'minor unit': 0, 'plural name': 'CFP francs', 'singular name': 'CFP franc', 'symbol': 'CFPF', 'narrow symbol': 'CFPF'},
    'YER': {'currency': 'Yemeni Rial', 'numeric code': 886, 'minor unit': 2, 'plural name': 'Yemeni rials', 'singular name': 'Yemeni rial', 'symbol': 'YER', 'narrow symbol': 'YER'},
    'ZAR': {'currency': 'Rand', 'numeric code': 710, 'minor unit': 2, 'plural name': 'South African rand', 'singular name': 'South African rand', 'symbol': 'ZAR', 'narrow symbol': 'R'},
    'ZMW': {'currency': 'Zambian Kwacha', 'numeric code': 967, 'minor unit': 2, 'plural name': 'Zambian kwachas', 'singular name': 'Zambian kwacha', 'symbol': 'ZMW', 'narrow symbol': 'ZK'},
    'ZWL': {'currency': 'Zimbabwe Dollar', 'numeric code': 932, 'minor unit': 2, 'plural name': 'Zimbabwean dollars (2009)', 'singular name': 'Zimbabwean dollar (2009)', 'symbol': 'ZWL', 'narrow symbol': 'ZWL'}
}


currency_list_iso4217 = [
    ('AFN', 'Afghani'),
    ('DZD', 'Algerian Dinar'),
    ('ARS', 'Argentine Peso'),
    ('AMD', 'Armenian Dram'),
    ('AWG', 'Aruban Florin'),
    ('AUD', 'Australian Dollar'),
    ('AZN', 'Azerbaijan Manat'),
    ('BSD', 'Bahamian Dollar'),
    ('BHD', 'Bahraini Dinar'),
    ('THB', 'Baht'),
    ('PAB', 'Balboa'),
    ('BBD', 'Barbados Dollar'),
    ('BYN', 'Belarusian Ruble'),
    ('BZD', 'Belize Dollar'),
    ('BMD', 'Bermudian Dollar'),
    ('BOB', 'Boliviano'),
    ('VES', 'Bolívar Soberano'),
    ('BRL', 'Brazilian Real'),
    ('BND', 'Brunei Dollar'),
    ('BGN', 'Bulgarian Lev'),
    ('BIF', 'Burundi Franc'),
    ('XOF', 'CFA Franc BCEAO'),
    ('XAF', 'CFA Franc BEAC'),
    ('XPF', 'CFP Franc'),
    ('CVE', 'Cabo Verde Escudo'),
    ('CAD', 'Canadian Dollar'),
    ('KYD', 'Cayman Islands Dollar'),
    ('CLP', 'Chilean Peso'),
    ('COP', 'Colombian Peso'),
    ('KMF', 'Comorian Franc '),
    ('CDF', 'Congolese Franc'),
    ('BAM', 'Convertible Mark'),
    ('NIO', 'Cordoba Oro'),
    ('CRC', 'Costa Rican Colon'),
    ('CUP', 'Cuban Peso'),
    ('CZK', 'Czech Koruna'),
    ('GMD', 'Dalasi'),
    ('DKK', 'Danish Krone'),
    ('MKD', 'Denar'),
    ('DJF', 'Djibouti Franc'),
    ('STN', 'Dobra'),
    ('DOP', 'Dominican Peso'),
    ('VND', 'Dong'),
    ('XCD', 'East Caribbean Dollar'),
    ('EGP', 'Egyptian Pound'),
    ('SVC', 'El Salvador Colon'),
    ('ETB', 'Ethiopian Birr'),
    ('EUR', 'Euro'),
    ('FKP', 'Falkland Islands Pound'),
    ('FJD', 'Fiji Dollar'),
    ('HUF', 'Forint'),
    ('GHS', 'Ghana Cedi'),
    ('GIP', 'Gibraltar Pound'),
    ('HTG', 'Gourde'),
    ('PYG', 'Guarani'),
    ('GNF', 'Guinean Franc'),
    ('GYD', 'Guyana Dollar'),
    ('HKD', 'Hong Kong Dollar'),
    ('UAH', 'Hryvnia'),
    ('ISK', 'Iceland Krona'),
    ('INR', 'Indian Rupee'),
    ('IRR', 'Iranian Rial'),
    ('IQD', 'Iraqi Dinar'),
    ('JMD', 'Jamaican Dollar'),
    ('JOD', 'Jordanian Dinar'),
    ('KES', 'Kenyan Shilling'),
    ('PGK', 'Kina'),
    ('HRK', 'Kuna'),
    ('KWD', 'Kuwaiti Dinar'),
    ('AOA', 'Kwanza'),
    ('MMK', 'Kyat'),
    ('LAK', 'Lao Kip'),
    ('GEL', 'Lari'),
    ('LBP', 'Lebanese Pound'),
    ('ALL', 'Lek'),
    ('HNL', 'Lempira'),
    ('SLL', 'Leone'),
    ('LRD', 'Liberian Dollar'),
    ('LYD', 'Libyan Dinar'),
    ('SZL', 'Lilangeni'),
    ('LSL', 'Loti'),
    ('MGA', 'Malagasy Ariary'),
    ('MWK', 'Malawi Kwacha'),
    ('MYR', 'Malaysian Ringgit'),
    ('MUR', 'Mauritius Rupee'),
    ('MXN', 'Mexican Peso'),
    ('MXV', 'Mexican Unidad de Inversion (UDI)'),
    ('MDL', 'Moldovan Leu'),
    ('MAD', 'Moroccan Dirham'),
    ('MZN', 'Mozambique Metical'),
    ('BOV', 'Mvdol'),
    ('NGN', 'Naira'),
    ('ERN', 'Nakfa'),
    ('NAD', 'Namibia Dollar'),
    ('NPR', 'Nepalese Rupee'),
    ('ANG', 'Netherlands Antillean Guilder'),
    ('ILS', 'New Israeli Sheqel'),
    ('TWD', 'New Taiwan Dollar'),
    ('NZD', 'New Zealand Dollar'),
    ('BTN', 'Ngultrum'),
    ('KPW', 'North Korean Won'),
    ('NOK', 'Norwegian Krone'),
    ('MRU', 'Ouguiya'),
    ('PKR', 'Pakistan Rupee'),
    ('MOP', 'Pataca'),
    ('TOP', 'Pa’anga'),
    ('CUC', 'Peso Convertible'),
    ('UYU', 'Peso Uruguayo'),
    ('PHP', 'Philippine Peso'),
    ('GBP', 'Pound Sterling'),
    ('BWP', 'Pula'),
    ('QAR', 'Qatari Rial'),
    ('GTQ', 'Quetzal'),
    ('ZAR', 'Rand'),
    ('OMR', 'Rial Omani'),
    ('KHR', 'Riel'),
    ('RON', 'Romanian Leu'),
    ('MVR', 'Rufiyaa'),
    ('IDR', 'Rupiah'),
    ('RUB', 'Russian Ruble'),
    ('RWF', 'Rwanda Franc'),
    ('SHP', 'Saint Helena Pound'),
    ('SAR', 'Saudi Riyal'),
    ('RSD', 'Serbian Dinar'),
    ('SCR', 'Seychelles Rupee'),
    ('SGD', 'Singapore Dollar'),
    ('PEN', 'Sol'),
    ('SBD', 'Solomon Islands Dollar'),
    ('KGS', 'Som'),
    ('SOS', 'Somali Shilling'),
    ('TJS', 'Somoni'),
    ('SSP', 'South Sudanese Pound'),
    ('LKR', 'Sri Lanka Rupee'),
    ('SDG', 'Sudanese Pound'),
    ('SRD', 'Surinam Dollar'),
    ('SEK', 'Swedish Krona'),
    ('CHF', 'Swiss Franc'),
    ('SYP', 'Syrian Pound'),
    ('BDT', 'Taka'),
    ('WST', 'Tala'),
    ('TZS', 'Tanzanian Shilling'),
    ('KZT', 'Tenge'),
    ('TTD', 'Trinidad and Tobago Dollar'),
    ('MNT', 'Tugrik'),
    ('TND', 'Tunisian Dinar'),
    ('TRY', 'Turkish Lira'),
    ('TMT', 'Turkmenistan New Manat'),
    ('AED', 'UAE Dirham'),
    ('USD', 'US Dollar'),
    ('USN', 'US Dollar (Next day)'),
    ('UGX', 'Uganda Shilling'),
    ('UYW', 'Unidad Previsional'),
    ('CLF', 'Unidad de Fomento'),
    ('COU', 'Unidad de Valor Real'),
    ('UYI', 'Uruguay Peso en Unidades Indexadas (UI)'),
    ('UZS', 'Uzbekistan Sum'),
    ('VUV', 'Vatu'),
    ('CHE', 'WIR Euro'),
    ('CHW', 'WIR Franc'),
    ('KRW', 'Won'),
    ('YER', 'Yemeni Rial'),
    ('JPY', 'Yen'),
    ('CNY', 'Yuan Renminbi'),
    ('ZMW', 'Zambian Kwacha'),
    ('ZWL', 'Zimbabwe Dollar'),
    ('PLN', 'Zloty')
]


currency_list_xe_plural = [
    ('AFN', 'Afghan afghanis'),
    ('ALL', 'Albanian lekë'),
    ('DZD', 'Algerian dinars'),
    ('AOA', 'Angolan kwanzas'),
    ('ARS', 'Argentine pesos'),
    ('AMD', 'Armenian drams'),
    ('AWG', 'Aruban florin'),
    ('AUD', 'Australian dollars'),
    ('AZN', 'Azerbaijani manats'),
    ('BSD', 'Bahamian dollars'),
    ('BHD', 'Bahraini dinars'),
    ('BDT', 'Bangladeshi takas'),
    ('BBD', 'Barbadian dollars'),
    ('BYN', 'Belarusian rubles'),
    ('BZD', 'Belize dollars'),
    ('BMD', 'Bermudan dollars'),
    ('BTN', 'Bhutanese ngultrums'),
    ('BOB', 'Bolivian bolivianos'),
    ('BOV', 'Bolivian mvdols'),
    ('BAM', 'Bosnia-Herzegovina convertible marks'),
    ('BWP', 'Botswanan pulas'),
    ('BRL', 'Brazilian reals'),
    ('GBP', 'British pounds'),
    ('BND', 'Brunei dollars'),
    ('BGN', 'Bulgarian leva'),
    ('BIF', 'Burundian francs'),
    ('XPF', 'CFP francs'),
    ('KHR', 'Cambodian riels'),
    ('CAD', 'Canadian dollars'),
    ('CVE', 'Cape Verdean escudos'),
    ('KYD', 'Cayman Islands dollars'),
    ('XAF', 'Central African CFA francs'),
    ('CLP', 'Chilean pesos'),
    ('CLF', 'Chilean units of account (UF)'),
    ('CNY', 'Chinese yuan'),
    ('COP', 'Colombian pesos'),
    ('COU', 'Colombian real value units'),
    ('KMF', 'Comorian francs'),
    ('CDF', 'Congolese francs'),
    ('CRC', 'Costa Rican colóns'),
    ('HRK', 'Croatian kunas'),
    ('CUC', 'Cuban convertible pesos'),
    ('CUP', 'Cuban pesos'),
    ('CZK', 'Czech korunas'),
    ('DKK', 'Danish kroner'),
    ('DJF', 'Djiboutian francs'),
    ('DOP', 'Dominican pesos'),
    ('XCD', 'East Caribbean dollars'),
    ('EGP', 'Egyptian pounds'),
    ('ERN', 'Eritrean nakfas'),
    ('ETB', 'Ethiopian birrs'),
    ('EUR', 'Euros'),
    ('FKP', 'Falkland Islands pounds'),
    ('FJD', 'Fijian dollars'),
    ('GMD', 'Gambian dalasis'),
    ('GEL', 'Georgian laris'),
    ('GHS', 'Ghanaian cedis'),
    ('GIP', 'Gibraltar pounds'),
    ('GTQ', 'Guatemalan quetzals'),
    ('GNF', 'Guinean francs'),
    ('GYD', 'Guyanaese dollars'),
    ('HTG', 'Haitian gourdes'),
    ('HNL', 'Honduran lempiras'),
    ('HKD', 'Hong Kong dollars'),
    ('HUF', 'Hungarian forints'),
    ('ISK', 'Icelandic krónur'),
    ('INR', 'Indian rupees'),
    ('IDR', 'Indonesian rupiahs'),
    ('IRR', 'Iranian rials'),
    ('IQD', 'Iraqi dinars'),
    ('ILS', 'Israeli new shekels'),
    ('JMD', 'Jamaican dollars'),
    ('JPY', 'Japanese yen'),
    ('JOD', 'Jordanian dinars'),
    ('KZT', 'Kazakhstani tenges'),
    ('KES', 'Kenyan shillings'),
    ('KWD', 'Kuwaiti dinars'),
    ('KGS', 'Kyrgystani soms'),
    ('LAK', 'Laotian kips'),
    ('LBP', 'Lebanese pounds'),
    ('LSL', 'Lesotho lotis'),
    ('LRD', 'Liberian dollars'),
    ('LYD', 'Libyan dinars'),
    ('MOP', 'Macanese patacas'),
    ('MKD', 'Macedonian denari'),
    ('MGA', 'Malagasy ariaries'),
    ('MWK', 'Malawian kwachas'),
    ('MYR', 'Malaysian ringgits'),
    ('MVR', 'Maldivian rufiyaas'),
    ('MRU', 'Mauritanian ouguiyas'),
    ('MUR', 'Mauritian rupees'),
    ('MXV', 'Mexican investment units'),
    ('MXN', 'Mexican pesos'),
    ('MDL', 'Moldovan lei'),
    ('MNT', 'Mongolian tugriks'),
    ('MAD', 'Moroccan dirhams'),
    ('MZN', 'Mozambican meticals'),
    ('MMK', 'Myanmar kyats'),
    ('NAD', 'Namibian dollars'),
    ('NPR', 'Nepalese rupees'),
    ('ANG', 'Netherlands Antillean guilders'),
    ('TWD', 'New Taiwan dollars'),
    ('NZD', 'New Zealand dollars'),
    ('NIO', 'Nicaraguan córdobas'),
    ('NGN', 'Nigerian nairas'),
    ('KPW', 'North Korean won'),
    ('NOK', 'Norwegian kroner'),
    ('OMR', 'Omani rials'),
    ('PKR', 'Pakistani rupees'),
    ('PAB', 'Panamanian balboas'),
    ('PGK', 'Papua New Guinean kina'),
    ('PYG', 'Paraguayan guaranis'),
    ('PEN', 'Peruvian soles'),
    ('PHP', 'Philippine pisos'),
    ('PLN', 'Polish zlotys'),
    ('QAR', 'Qatari rials'),
    ('RON', 'Romanian lei'),
    ('RUB', 'Russian rubles'),
    ('RWF', 'Rwandan francs'),
    ('SVC', 'Salvadoran colones'),
    ('WST', 'Samoan tala'),
    ('SAR', 'Saudi riyals'),
    ('RSD', 'Serbian dinars'),
    ('SCR', 'Seychellois rupees'),
    ('SLL', 'Sierra Leonean leones'),
    ('SGD', 'Singapore dollars'),
    ('SBD', 'Solomon Islands dollars'),
    ('SOS', 'Somali shillings'),
    ('ZAR', 'South African rand'),
    ('KRW', 'South Korean won'),
    ('SSP', 'South Sudanese pounds'),
    ('LKR', 'Sri Lankan rupees'),
    ('SHP', 'St. Helena pounds'),
    ('SDG', 'Sudanese pounds'),
    ('SRD', 'Surinamese dollars'),
    ('SZL', 'Swazi emalangeni'),
    ('SEK', 'Swedish kronor'),
    ('CHF', 'Swiss francs'),
    ('SYP', 'Syrian pounds'),
    ('STN', 'São Tomé & Príncipe dobras'),
    ('TJS', 'Tajikistani somonis'),
    ('TZS', 'Tanzanian shillings'),
    ('THB', 'Thai baht'),
    ('TOP', 'Tongan paʻanga'),
    ('TTD', 'Trinidad & Tobago dollars'),
    ('TND', 'Tunisian dinars'),
    ('TRY', 'Turkish Lira'),
    ('TMT', 'Turkmenistani manat'),
    ('AED', 'UAE dirhams'),
    ('USD', 'US dollars'),
    ('USN', 'US dollars (next day)'),
    ('UGX', 'Ugandan shillings'),
    ('UAH', 'Ukrainian hryvnias'),
    ('UYW', 'Uruguayan nominal wage index units'),
    ('UYU', 'Uruguayan pesos'),
    ('UYI', 'Uruguayan pesos (indexed units)'),
    ('UZS', 'Uzbekistani som'),
    ('VUV', 'Vanuatu vatus'),
    ('VES', 'Venezuelan bolívars'),
    ('VND', 'Vietnamese dong'),
    ('CHE', 'WIR euros'),
    ('CHW', 'WIR francs'),
    ('XOF', 'West African CFA francs'),
    ('YER', 'Yemeni rials'),
    ('ZMW', 'Zambian kwachas'),
    ('ZWL', 'Zimbabwean dollars (2009)')
]


currency_list_xe_singular = [
    ('AFN', 'Afghan afghani'),
    ('ALL', 'Albanian lek'),
    ('DZD', 'Algerian dinar'),
    ('AOA', 'Angolan kwanza'),
    ('ARS', 'Argentine peso'),
    ('AMD', 'Armenian dram'),
    ('AWG', 'Aruban florin'),
    ('AUD', 'Australian dollar'),
    ('AZN', 'Azerbaijani manat'),
    ('BSD', 'Bahamian dollar'),
    ('BHD', 'Bahraini dinar'),
    ('BDT', 'Bangladeshi taka'),
    ('BBD', 'Barbadian dollar'),
    ('BYN', 'Belarusian ruble'),
    ('BZD', 'Belize dollar'),
    ('BMD', 'Bermudan dollar'),
    ('BTN', 'Bhutanese ngultrum'),
    ('BOB', 'Bolivian boliviano'),
    ('BOV', 'Bolivian mvdol'),
    ('BAM', 'Bosnia-Herzegovina convertible mark'),
    ('BWP', 'Botswanan pula'),
    ('BRL', 'Brazilian real'),
    ('GBP', 'British pound'),
    ('BND', 'Brunei dollar'),
    ('BGN', 'Bulgarian lev'),
    ('BIF', 'Burundian franc'),
    ('XPF', 'CFP franc'),
    ('KHR', 'Cambodian riel'),
    ('CAD', 'Canadian dollar'),
    ('CVE', 'Cape Verdean escudo'),
    ('KYD', 'Cayman Islands dollar'),
    ('XAF', 'Central African CFA franc'),
    ('CLP', 'Chilean peso'),
    ('CLF', 'Chilean unit of account (UF)'),
    ('CNY', 'Chinese yuan'),
    ('COP', 'Colombian peso'),
    ('COU', 'Colombian real value unit'),
    ('KMF', 'Comorian franc'),
    ('CDF', 'Congolese franc'),
    ('CRC', 'Costa Rican colón'),
    ('HRK', 'Croatian kuna'),
    ('CUC', 'Cuban convertible peso'),
    ('CUP', 'Cuban peso'),
    ('CZK', 'Czech koruna'),
    ('DKK', 'Danish krone'),
    ('DJF', 'Djiboutian franc'),
    ('DOP', 'Dominican peso'),
    ('XCD', 'East Caribbean dollar'),
    ('EGP', 'Egyptian pound'),
    ('ERN', 'Eritrean nakfa'),
    ('ETB', 'Ethiopian birr'),
    ('EUR', 'Euro'),
    ('FKP', 'Falkland Islands pound'),
    ('FJD', 'Fijian dollar'),
    ('GMD', 'Gambian dalasi'),
    ('GEL', 'Georgian lari'),
    ('GHS', 'Ghanaian cedi'),
    ('GIP', 'Gibraltar pound'),
    ('GTQ', 'Guatemalan quetzal'),
    ('GNF', 'Guinean franc'),
    ('GYD', 'Guyanaese dollar'),
    ('HTG', 'Haitian gourde'),
    ('HNL', 'Honduran lempira'),
    ('HKD', 'Hong Kong dollar'),
    ('HUF', 'Hungarian forint'),
    ('ISK', 'Icelandic króna'),
    ('INR', 'Indian rupee'),
    ('IDR', 'Indonesian rupiah'),
    ('IRR', 'Iranian rial'),
    ('IQD', 'Iraqi dinar'),
    ('ILS', 'Israeli new shekel'),
    ('JMD', 'Jamaican dollar'),
    ('JPY', 'Japanese yen'),
    ('JOD', 'Jordanian dinar'),
    ('KZT', 'Kazakhstani tenge'),
    ('KES', 'Kenyan shilling'),
    ('KWD', 'Kuwaiti dinar'),
    ('KGS', 'Kyrgystani som'),
    ('LAK', 'Laotian kip'),
    ('LBP', 'Lebanese pound'),
    ('LSL', 'Lesotho loti'),
    ('LRD', 'Liberian dollar'),
    ('LYD', 'Libyan dinar'),
    ('MOP', 'Macanese pataca'),
    ('MKD', 'Macedonian denar'),
    ('MGA', 'Malagasy ariary'),
    ('MWK', 'Malawian kwacha'),
    ('MYR', 'Malaysian ringgit'),
    ('MVR', 'Maldivian rufiyaa'),
    ('MRU', 'Mauritanian ouguiya'),
    ('MUR', 'Mauritian rupee'),
    ('MXV', 'Mexican investment unit'),
    ('MXN', 'Mexican peso'),
    ('MDL', 'Moldovan leu'),
    ('MNT', 'Mongolian tugrik'),
    ('MAD', 'Moroccan dirham'),
    ('MZN', 'Mozambican metical'),
    ('MMK', 'Myanmar kyat'),
    ('NAD', 'Namibian dollar'),
    ('NPR', 'Nepalese rupee'),
    ('ANG', 'Netherlands Antillean guilder'),
    ('TWD', 'New Taiwan dollar'),
    ('NZD', 'New Zealand dollar'),
    ('NIO', 'Nicaraguan córdoba'),
    ('NGN', 'Nigerian naira'),
    ('KPW', 'North Korean won'),
    ('NOK', 'Norwegian krone'),
    ('OMR', 'Omani rial'),
    ('PKR', 'Pakistani rupee'),
    ('PAB', 'Panamanian balboa'),
    ('PGK', 'Papua New Guinean kina'),
    ('PYG', 'Paraguayan guarani'),
    ('PEN', 'Peruvian sol'),
    ('PHP', 'Philippine piso'),
    ('PLN', 'Polish zloty'),
    ('QAR', 'Qatari rial'),
    ('RON', 'Romanian leu'),
    ('RUB', 'Russian ruble'),
    ('RWF', 'Rwandan franc'),
    ('SVC', 'Salvadoran colón'),
    ('WST', 'Samoan tala'),
    ('SAR', 'Saudi riyal'),
    ('RSD', 'Serbian dinar'),
    ('SCR', 'Seychellois rupee'),
    ('SLL', 'Sierra Leonean leone'),
    ('SGD', 'Singapore dollar'),
    ('SBD', 'Solomon Islands dollar'),
    ('SOS', 'Somali shilling'),
    ('ZAR', 'South African rand'),
    ('KRW', 'South Korean won'),
    ('SSP', 'South Sudanese pound'),
    ('LKR', 'Sri Lankan rupee'),
    ('SHP', 'St. Helena pound'),
    ('SDG', 'Sudanese pound'),
    ('SRD', 'Surinamese dollar'),
    ('SZL', 'Swazi lilangeni'),
    ('SEK', 'Swedish krona'),
    ('CHF', 'Swiss franc'),
    ('SYP', 'Syrian pound'),
    ('STN', 'São Tomé & Príncipe dobra'),
    ('TJS', 'Tajikistani somoni'),
    ('TZS', 'Tanzanian shilling'),
    ('THB', 'Thai baht'),
    ('TOP', 'Tongan paʻanga'),
    ('TTD', 'Trinidad & Tobago dollar'),
    ('TND', 'Tunisian dinar'),
    ('TRY', 'Turkish lira'),
    ('TMT', 'Turkmenistani manat'),
    ('AED', 'UAE dirham'),
    ('USD', 'US dollar'),
    ('USN', 'US dollar (next day)'),
    ('UGX', 'Ugandan shilling'),
    ('UAH', 'Ukrainian hryvnia'),
    ('UYW', 'Uruguayan nominal wage index unit'),
    ('UYU', 'Uruguayan peso'),
    ('UYI', 'Uruguayan peso (indexed units)'),
    ('UZS', 'Uzbekistani som'),
    ('VUV', 'Vanuatu vatu'),
    ('VES', 'Venezuelan bolívar'),
    ('VND', 'Vietnamese dong'),
    ('CHE', 'WIR euro'),
    ('CHW', 'WIR franc'),
    ('XOF', 'West African CFA franc'),
    ('YER', 'Yemeni rial'),
    ('ZMW', 'Zambian kwacha'),
    ('ZWL', 'Zimbabwean dollar (2009)')
]